CREATE TABLE IF NOT EXISTS chat_rooms (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	"name" varchar(255) NULL,
	"type" varchar(20) DEFAULT 'PRIVATE'::character varying NOT NULL,
	created_by int4 NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	last_message_at timestamptz NULL,
	last_message_text text NULL,
	last_message_sender_id int4 NULL,
	avatar_url varchar(500) NULL,
	description text NULL,
	is_active bool DEFAULT true NULL,
	max_participants int4 DEFAULT 2 NULL,
	CONSTRAINT chat_rooms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id),
	CONSTRAINT chat_rooms_last_message_sender_id_fkey FOREIGN KEY (last_message_sender_id) REFERENCES users(id)
);