CREATE TABLE IF NOT EXISTS chat_participants (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	chat_id int4 NULL,
	user_id int4 NULL,
	joined_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	"role" varchar(20) DEFAULT 'MEMBER'::character varying NULL,
	is_active bool DEFAULT true NULL,
	last_read_at timestamptz NULL,
	CONSTRAINT chat_participants_chat_id_user_id_key UNIQUE (chat_id, user_id),
	CONSTRAINT chat_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT chat_participants_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chat_rooms(id)

);