CREATE TABLE IF NOT EXISTS messages (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	chat_id int4 NULL,
	sender_id int4 NULL,
	"content" text NOT NULL,
	message_type varchar(20) DEFAULT 'TEXT'::character varying NULL,
	sent_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	delivered_at timestamptz NULL,
	read_at timestamptz NULL,
	reply_to_message_id int4 NULL,
	is_edited bool DEFAULT false NULL,
	edited_at timestamptz NULL,
	CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chat_rooms(id),
	CONSTRAINT messages_reply_to_message_id_fkey FOREIGN KEY (reply_to_message_id) REFERENCES messages(id),
	CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id)
);