spring.application.name=CuppaApp
server.port=8080
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cuppa_db
spring.datasource.username=cuppa_user
spring.datasource.password=cuppa_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql


# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=kXp2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7w!z%C*F?
app.jwt.expiration=86400000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Actuator Configuration
management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.endpoints.web.base-path=/actuator
management.endpoints.enabled-by-default=true
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.metrics.enabled=true
management.endpoint.info.enabled=true
management.info.env.enabled=true
# Custom metrics
management.metrics.export.prometheus.enabled=true
management.metrics.enable.all=true
# Static content
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
