CREATE TABLE IF NOT EXISTS users (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	username varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	password_hash varchar(255) NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	avatar_url varchar(255) NULL,
	phone varchar(255) NULL,
	is_online bool DEFAULT false NULL,
	last_seen timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS chat_rooms (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	"name" varchar(255) NULL,
	"type" varchar(20) DEFAULT 'PRIVATE'::character varying NOT NULL,
	created_by int4 NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	last_message_at timestamptz NULL,
	last_message_text text NULL,
	last_message_sender_id int4 NULL,
	avatar_url varchar(500) NULL,
	description text NULL,
	is_active bool DEFAULT true NULL,
	max_participants int4 DEFAULT 2 NULL,
	CONSTRAINT chat_rooms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id),
	CONSTRAINT chat_rooms_last_message_sender_id_fkey FOREIGN KEY (last_message_sender_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_chat_rooms_last_message_at ON chat_rooms USING btree (last_message_at DESC);

CREATE TABLE IF NOT EXISTS chat_participants (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	chat_id int4 NULL,
	user_id int4 NULL,
	joined_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	"role" varchar(20) DEFAULT 'MEMBER'::character varying NULL,
	is_active bool DEFAULT true NULL,
	last_read_at timestamptz NULL,
	CONSTRAINT chat_participants_chat_id_user_id_key UNIQUE (chat_id, user_id),
	CONSTRAINT chat_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT chat_participants_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chat_rooms(id)

);

CREATE TABLE IF NOT EXISTS messages (
	id INT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) PRIMARY KEY NOT NULL,
	chat_id int4 NULL,
	sender_id int4 NULL,
	"content" text NOT NULL,
	message_type varchar(20) DEFAULT 'TEXT'::character varying NULL,
	sent_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	delivered_at timestamptz NULL,
	read_at timestamptz NULL,
	reply_to_message_id int4 NULL,
	is_edited bool DEFAULT false NULL,
	edited_at timestamptz NULL,
	CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES chat_rooms(id),
	CONSTRAINT messages_reply_to_message_id_fkey FOREIGN KEY (reply_to_message_id) REFERENCES messages(id),
	CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_messages_chat_id_sent_at ON messages USING btree (chat_id, sent_at DESC);
